/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#006c46',
          container: '#00b074',
          fixed: '#73fbb8',
          'fixed-dim': '#53de9e',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#003a23',
        'on-primary-fixed': '#002112',
        'on-primary-fixed-variant': '#005233',
        'inverse-primary': '#53de9e',
        secondary: {
          DEFAULT: '#0054cd',
          container: '#316ee9',
          fixed: '#dae2ff',
          'fixed-dim': '#b2c5ff',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'on-secondary-fixed': '#001847',
        'on-secondary-fixed-variant': '#0040a1',
        tertiary: {
          DEFAULT: '#5c5f60',
          container: '#989a9b',
          fixed: '#e1e3e4',
          'fixed-dim': '#c5c7c8',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#2f3233',
        'on-tertiary-fixed': '#191c1d',
        'on-tertiary-fixed-variant': '#454748',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: {
          DEFAULT: '#f4fbf3',
          dim: '#d5dcd4',
          bright: '#f4fbf3',
          container: {
            DEFAULT: '#e8f0e8',
            low: '#eef6ee',
            high: '#e3eae2',
            highest: '#dde4dd',
            lowest: '#ffffff',
          },
        },
        'on-surface': '#161d19',
        'on-surface-variant': '#3d4a41',
        'inverse-surface': '#2b322d',
        'inverse-on-surface': '#ebf3eb',
        outline: {
          DEFAULT: '#6c7a70',
          variant: '#bccabf',
        },
        background: '#f4fbf3',
        'on-background': '#161d19',
        'surface-variant': '#dde4dd',
        'surface-tint': '#006c46',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '280px',
        'section-margin': '40px',
        'card-gap': '16px',
        'max-width-content': '1200px',
        'unit': '4px',
        'container-padding': '24px',
      },
      fontFamily: {
        'body-md': ['"Public Sans"', 'sans-serif'],
        'timestamp': ['"Inter"', 'sans-serif'],
        'headline-lg': ['"Public Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Public Sans"', 'sans-serif'],
        'title-md': ['"Public Sans"', 'sans-serif'],
        'display-lg': ['"Public Sans"', 'sans-serif'],
        'body-lg': ['"Public Sans"', 'sans-serif'],
        'label-sm': ['"Inter"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'timestamp': ['11px', { lineHeight: '14px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        'ambient': '0px 4px 20px rgba(0,0,0,0.04)',
        'floating': '0px 8px 32px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
